name: gh-token-gen
description: generate GitHub application token
inputs:
  app-id:
    description: GitHub Application ID (or Client ID)
    required: true
  private-key:
    description: The application's PEM-encoded private key
    required: true
outputs:
  token:
    description: Generated token
runs:
  using: node20
  main: index.cjs
