---
name: gh-token-gen
description: generate GitHub application token
inputs:
  app-id:
    required: true
    description: GitHub Application ID (or Client ID)
  private-key:
    required: true
    description: "The application's PEM-encoded private key"
outputs:
  token:
    description: Generated token
runs:
  using: node24
  main: index.cjs
  post: index.cjs
