name: Release / Create Pull Request
on:
  workflow_dispatch:
  pull_request:
    paths:
      # to debug this workflow
      - .github/workflows/release--create-pr.yaml
      - .releaserc.yaml

permissions:
  contents: write
  pull-requests: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@0cdefe1224944c23645e5131f7a5189672c0df92 # v4

  create:
    concurrency:
      group: ${{ github.workflow }}-semantic-release
    needs: get-next-version
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: EricCrosson/install-github-release-binary@cf6839a47efeebb26b9210dd0832546420a8dc63 # v2
        with:
          targets: semantic-release-cargo/semantic-release-cargo@v2.2.96
      - run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}
      - id: gh-token-gen
        uses: oakcask/gh-token-gen@d65c585678cb39f009f96046d788617e1d0b0745 # v4.0.2
        with:
          app-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: int128/update-generated-files-action@9662c04ea188ea4238f93acda9e35e2edc49a385 # v2
        with:
          title: "chore: prepare v${{ needs.get-next-version.outputs.new-release-version }}"
          body: Prepare releasing v${{ needs.get-next-version.outputs.new-release-version }}
          commit-message: "chore: prepare v${{ needs.get-next-version.outputs.new-release-version }}"
          token: ${{ steps.gh-token-gen.outputs.token }}
