name: Release / Publish
on:
  push:
    branches:
      - main
    paths:
      # trigger after merging release PRs
      - CHANGELOG.md
  pull_request:
    paths:
      # to develop or debug this workflow
      - .github/workflows/release--publish.yaml

permissions:
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      full: ${{ steps.get-version.outputs.full }}
      semver_major: ${{ steps.get-version.outputs.major }}
      semver_minor: ${{ steps.get-version.outputs.minor }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "full=${VERSION}" >> $GITHUB_OUTPUT
          echo "major=$(echo "${VERSION}" | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "minor=$(echo "${VERSION}" | cut -d. -f1-2)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-pack
          version: "0.13.1"
      - run: wasm-pack build --target=nodejs . --locked
      - run: |
          mkdir -p dist/pkg
          cp -t dist/pkg/ pkg/*.js pkg/*.wasm
          cp -t dist/ index.cjs action.yaml LICENSE* *.md
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  tag:
    runs-on: ubuntu-latest
    needs:
      - build
      - get-version
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: github-actions
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - run: git diff --stat || true
      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore: v${{ needs.get-version.outputs.full }}"
          git tag -a "v${{ needs.get-version.outputs.full }}" -m "v${{ needs.get-version.outputs.full }}"
          git push origin "v${{ needs.get-version.outputs.full }}"
          git tag -d "v${{ needs.get-version.outputs.semver_major }}" || true
          git tag -a "v${{ needs.get-version.outputs.semver_major }}" -m "v${{ needs.get-version.outputs.semver_major }}"
          git tag -d "v${{ needs.get-version.outputs.semver_minor }}" || true
          git tag -a "v${{ needs.get-version.outputs.semver_minor }}" -m "v${{ needs.get-version.outputs.semver_minor }}"
          git push origin ":v${{ needs.get-version.outputs.semver_major }}" || true
          git push origin "v${{ needs.get-version.outputs.semver_major }}"
          git push origin ":v${{ needs.get-version.outputs.semver_minor }}" || true
          git push origin "v${{ needs.get-version.outputs.semver_minor }}"
      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          gh release create "v${{ needs.get-version.outputs.full }}" \
            --title "v${{ needs.get-version.outputs.full }}" \
            --generate-notes
