name: Release
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      # to develop or debug this workflow
      - .github/workflows/release.yaml
      - .releaserc.yaml

jobs:
  get-next-version:
    permissions:
      contents: write
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  cargo-toml-updated:
    runs-on: ubuntu-latest
    needs:
      - get-next-version
    outputs:
      updated: ${{ steps.check-updated.outputs.updated }}
    steps:
      - uses: actions/checkout@v4
      - uses: EricCrosson/install-github-release-binary@v2
        with:
          targets: semantic-release-cargo/semantic-release-cargo@v2.2.96
        if: needs.get-next-version.outputs.new-release-published == 'true'
      - run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}
        if: needs.get-next-version.outputs.new-release-published == 'true'
      - id: check-updated
        run: git diff --exit-code && echo "updated=true" >> "$GITHUB_OUTPUT"
        # wanted not to workflow status being failure. 
        continue-on-error: true

  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs:
      - get-next-version
      - cargo-toml-updated
    if: ${{ needs.get-next-version.outputs.new-release-published == 'true' && needs.cargo-toml-updated.outputs.updated == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
