name: Release / Prepare
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      # to debug this workflow
      - .github/workflows/release--prepare.yaml
      - .releaserc.yaml

permissions:
  contents: write
  pull-requests: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  semantic-release:
    concurrency:
      group: ${{ github.workflow }}
    needs: get-next-version
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: EricCrosson/install-github-release-binary@v2
        with:
          targets: semantic-release-cargo/semantic-release-cargo@v2.2.96
      - run: semantic-release-cargo prepare ${{ needs.get-next-version.outputs.new-release-version }}
      - id: gh-token-gen
        uses: oakcask/gh-token-gen@v2.0.0
        with:
          app-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: int128/update-generated-files-action@v2
        with:
          title: "chore: prepare v${{ needs.get-next-version.outputs.new-release-version }}"
          body: Prepare releasing v${{ needs.get-next-version.outputs.new-release-version }}
          commit-message: "chore: prepare v${{ needs.get-next-version.outputs.new-release-version }}"
          token: ${{ steps.gh-token-gen.outputs.token }}
      - uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: "24.2.3"
          dry_run: ${{ github.ref != 'refs/heads/main' }}
        env: 
          GITHUB_TOKEN: ${{ steps.gh-token-gen.outputs.token }}
